version: "3.7"

services:
        
  localstack-s3test:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
    image: localstack/localstack
    container_name: localstack-s3test
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-west-2
    ports:
      - "4572:4572"
      - "8080:8080"

  s3testsapp:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: s3testsapp
    depends_on:
      - localstack-s3test
    environment:
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
